@startuml

class User {
-login
-password
+login()
+callAdmin()
+workOnComputer()
+makePrintRequest()
+takeDocument()
}

class AdvancedUser {
    -advancedSkillsList
    +doAdvancedJob()
}

class Administrator {
    -beardColor
    -superPowerList
    +fixServer()
    +fixPrinter()
}

class Computer {
    -OS
    +sendPrintRequest()
}

class Client {
    +connectToServer()
}

class Server {
    +goDown()
    +addToPrintingQueue()
}

class PrintServer {
    -printingQueue
    +sendForPrint()
}

class Printer {
    -model
    -type
    +print()
}

Client "1..*" -- "1..*" Server : connected to
Administrator "1..*" --> "1..*" Printer : fixing
User <|-- AdvancedUser
AdvancedUser <|-- Administrator
Computer <|-- Server
Computer <|-- Client
Printer "0..*" -- "1" PrintServer : connected to
Server "1" --> "1" PrintServer : sends print requests
User  --> Client : works on
Administrator "1..*" --> "1..*" Server : administrating
User "1" --> "1" Administrator : calls
Printer --> Document : prints
@enduml